query MyQuery {
  hackathon_idea_status(where: {idea_id_map: {hackathon_id: {_eq: "e606ae64-7c92-4344-94ad-4d0684458bcf"}}}) {
    idea_id_map {
      description
      title
    }
    status_id_map {
      label
    }
    status_id
    idea_id
  }
  hackathon_ideas_members(where: {ideas_id_map: {hackathon_id_map: {id: {_eq: "e606ae64-7c92-4344-94ad-4d0684458bcf"}}}}) {
    user_id_map {
      avatarUrl
      displayName
    }
    idea_id
  }
}
