import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ReactPlay Hackathon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://reactplay.io">rectplay</a>-
          <a href="https://nhost.io">nhost</a> Hackathon
        </h1>
        <Link href="/registration">
          <a>
            <h2>Register</h2>
          </a>
        </Link>
      </main>
    </div>
  );
}
